# http://docs.travis-ci.com/user/languages/c/
# start from https://github.com/rubinius/rubinius/blob/master/.travis.yml
language: c
sudo: false

compiler:
  - clang
  - gcc
os:
  - linux

matrix:
  allow_failures:
    - compiler: clang

# https://blog.lukaspradel.com/continuous-integration-for-cmake-projects-using-travis-ci/  
script:
  - make -j2 && ./pachi -u t-unit/sar.t
